########################################################################################################################
#                                                                                                                      #
#                                      Postprocessing networks -- Configuration file                                   #
#                                                                                                                      #
#                                           Lionel Cheng, CERFACS, 05.11.2020                                          #
#                                                                                                                      #
########################################################################################################################

# Contains the parameters for the model (training, etc.)

# To import the parameters, use
#     import yaml
#     with open('config.yml', 'r') as yaml_stream:
#         config = yaml.safe_load(yaml_stream)

casename: '3-networks/initial_cond/'

data:
  main_dir: '../outputs/3-networks/log/'
  trainings: {"UNet6 - random_8_1":"config_2/random_8/",
    "UNet6 - random_8_2":"config_4/random_8/",
    "UNet6 - random_16_1":"config_2/random_16/",
    "UNet6 - random_16_2":"config_4/random_16/"}
output:
  losses:
    var_dir: 'ComposedLosses'
    variables: ['DirichletBoundaryLoss', 'LaplacianLoss']
    data_types: ['train', 'valid']
  metrics:
    var_dir: 'Metrics'
    variables: ['residual', 'Eresidual']
    data_types: ['train', 'valid']