#!/bin/bash -l
#SBATCH --job-name perfs
#SBATCH --time=00:30:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=128
#SBATCH --partition rome
#SBATCH --nodelist krakenepyc2

export LD_LIBRARY_PATH=/softs/local_intel/petsc/3.13.4/lib:$LD_LIBRARY_PATH
nb_cpu=$SLURM_NPROCS

module list

# mpirun -np $nb_cpu ./poisson.out $1 $1 -ksp_type cg -ksp_norm_type unpreconditioned \
#     -pc_type gamg -gamg_est_ksp_type cg -gamg_est_ksp_max_it 10 -pc_gamg_process_eq_limit 500 \
#     -pc_gamg_coarse_eq_limit 1000 -mg_levels_esteig_ksp_type cg -mg_levels_esteig_ksp_max_it 10 \
#     -mg_levels_pc_type sor -mg_levels_ksp_type richardson

casename=A100
mkdir log/"${casename}"

mpirun -np $nb_cpu ./poisson.out 101 101 log/"${casename}"/solver_cg_gamg_"${nb_cpu}"_procs_101.log -ksp_type cg -ksp_rtol 1.e-6 -pc_type gamg
mpirun -np $nb_cpu ./poisson.out 201 201 log/"${casename}"/solver_cg_gamg_"${nb_cpu}"_procs_201.log -ksp_type cg -ksp_rtol 1.e-6 -pc_type gamg
mpirun -np $nb_cpu ./poisson.out 401 401 log/"${casename}"/solver_cg_gamg_"${nb_cpu}"_procs_401.log -ksp_type cg -ksp_rtol 1.e-6 -pc_type gamg
mpirun -np $nb_cpu ./poisson.out 801 801 log/"${casename}"/solver_cg_gamg_"${nb_cpu}"_procs_801.log -ksp_type cg -ksp_rtol 1.e-6 -pc_type gamg
mpirun -np $nb_cpu ./poisson.out 2001 2001 log/"${casename}"/solver_cg_gamg_"${nb_cpu}"_procs_2001.log -ksp_type cg -ksp_rtol 1.e-6 -pc_type gamg
mpirun -np $nb_cpu ./poisson.out 4001 4001 log/"${casename}"/solver_cg_gamg_"${nb_cpu}"_procs_4001.log -ksp_type cg -ksp_rtol 1.e-6 -pc_type gamg
mpirun -np $nb_cpu ./poisson.out 5001 5001 log/"${casename}"/solver_cg_gamg_"${nb_cpu}"_procs_5001.log -ksp_type cg -ksp_rtol 1.e-6 -pc_type gamg
