#!/bin/bash -l
#SBATCH --job-name perfs
#SBATCH --time=00:30:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=36
#SBATCH --partition biggpu

export LD_LIBRARY_PATH=/softs/local_intel/petsc/3.13.4/lib:$LD_LIBRARY_PATH
nb_cpu=$SLURM_NPROCS

source utils_cart.sh

# # Study different solvers for cartesian matrix
# # CG-GAMG / CG-Hypre-bommerang / LU and Cholesky

# rtol="1.0e-3"
# casedir="log/cart/solvers_rtol_1e-3/default"

# # --------------------------------------------
# # PETsc native GAMG with multiple Krylov solvers
# # --------------------------------------------
# krylov="cg"
# precond="gamg"
# casename="$casedir"/"$krylov"_"$precond"/"$nb_cpu"_procs/
# mkdir -p "${casename}"
# run_solver_cart "${nb_cpu}" "$krylov" "$precond" "${rtol}" "${casename}"

# krylov="gmres"
# precond="gamg"
# casename="$casedir"/"$krylov"_"$precond"/"$nb_cpu"_procs/
# mkdir -p "${casename}"
# run_solver_cart "${nb_cpu}" "$krylov" "$precond" "${rtol}" "${casename}"

# # Other Krylov solvers with GAMG
# krylov="minres"
# precond="gamg"
# casename="$casedir"/"$krylov"_"$precond"/"$nb_cpu"_procs/
# mkdir -p "${casename}"
# run_solver_cart "${nb_cpu}" "$krylov" "$precond" "${rtol}" "${casename}"

# krylov="bcgs"
# precond="gamg"
# casename="$casedir"/"$krylov"_"$precond"/"$nb_cpu"_procs/
# mkdir -p "${casename}"
# run_solver_cart "${nb_cpu}" "$krylov" "$precond" "${rtol}" "${casename}"

# krylov="cgs"
# precond="gamg"
# casename="$casedir"/"$krylov"_"$precond"/"$nb_cpu"_procs/
# mkdir -p "${casename}"
# run_solver_cart "${nb_cpu}" "$krylov" "$precond" "${rtol}" "${casename}"

# # --------------------------------------------
# # Hypre-BoomerAMG with multiple Krylov solvers
# # --------------------------------------------
# krylov="cg"
# precond="boomeramg"
# casename="$casedir"/"$krylov"_"$precond"/"$nb_cpu"_procs/
# mkdir -p "${casename}"
# run_hypre_boomeramg "${nb_cpu}" "$krylov" "${rtol}" "${casename}"

# krylov="gmres"
# precond="boomeramg"
# casename="$casedir"/"$krylov"_"$precond"/"$nb_cpu"_procs/
# mkdir -p "${casename}"
# run_hypre_boomeramg "${nb_cpu}" "$krylov" "${rtol}" "${casename}"

# # Other Krylov solvers with GAMG
# krylov="minres"
# precond="boomeramg"
# casename="$casedir"/"$krylov"_"$precond"/"$nb_cpu"_procs/
# mkdir -p "${casename}"
# run_hypre_boomeramg "${nb_cpu}" "$krylov" "${rtol}" "${casename}"

# krylov="bcgs"
# precond="boomeramg"
# casename="$casedir"/"$krylov"_"$precond"/"$nb_cpu"_procs/
# mkdir -p "${casename}"
# run_hypre_boomeramg "${nb_cpu}" "$krylov" "${rtol}" "${casename}"

# krylov="cgs"
# precond="boomeramg"
# casename="$casedir"/"$krylov"_"$precond"/"$nb_cpu"_procs/
# mkdir -p "${casename}"
# run_hypre_boomeramg "${nb_cpu}" "$krylov" "${rtol}" "${casename}"


# Run for 1e-7 precision
rtol="1.0e-7"
casedir="log/cart/solvers_rtol_1e-7/default"
krylov="cg"
precond="boomeramg"
casename="$casedir"/"$krylov"_"$precond"/"$nb_cpu"_procs/
mkdir -p "${casename}"
run_hypre_boomeramg "${nb_cpu}" "$krylov" "${rtol}" "${casename}"

# # Run for 1e-7 precision
# rtol="1.0e-12"
# casedir="log/cart/solvers_rtol_1e-12/default"
# krylov="cg"
# precond="boomeramg"
# casename="$casedir"/"$krylov"_"$precond"/"$nb_cpu"_procs/
# mkdir -p "${casename}"
# run_hypre_boomeramg "${nb_cpu}" "$krylov" "${rtol}" "${casename}"