#!/bin/bash -l
#SBATCH --job-name perfs
#SBATCH --time=00:30:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=36
#SBATCH --partition biggpu

source utils_cart.sh

export LD_LIBRARY_PATH=/softs/local_intel/petsc/3.13.4/lib:$LD_LIBRARY_PATH

rtol="1.0e-3"
nb_cpu=9
casename=log/cart/scaling/cg_gamg/"$nb_cpu"_procs/rtol_1e-3
mkdir -p "${casename}"
run_cg_gamg "${nb_cpu}" "${rtol}" "${casename}"

nb_cpu=18
casename=log/cart/scaling/cg_gamg/"$nb_cpu"_procs/rtol_1e-3
mkdir -p "${casename}"
run_cg_gamg "${nb_cpu}" "${rtol}" "${casename}"

nb_cpu=36
casename=log/cart/scaling/cg_gamg/"$nb_cpu"_procs/rtol_1e-3
mkdir -p "${casename}"
run_cg_gamg "${nb_cpu}" "${rtol}" "${casename}"