#!/bin/bash -l
#SBATCH --job-name perfs
#SBATCH --time=00:30:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=36
#SBATCH --partition biggpu

export LD_LIBRARY_PATH=/softs/local_intel/petsc/3.13.4/lib:$LD_LIBRARY_PATH
nb_cpu=$SLURM_NPROCS

# mpirun -np $nb_cpu ./poisson.out $1 $1 -ksp_type cg -ksp_norm_type unpreconditioned \
#     -pc_type gamg -gamg_est_ksp_type cg -gamg_est_ksp_max_it 10 -pc_gamg_process_eq_limit 500 \
#     -pc_gamg_coarse_eq_limit 1000 -mg_levels_esteig_ksp_type cg -mg_levels_esteig_ksp_max_it 10 \
#     -mg_levels_pc_type sor -mg_levels_ksp_type richardson

run_cg_gamg() {
    for nn in 101 201 401 801 2001 4001
    do
        mpirun -np "$nb_cpu" ./poisson.out $nn $nn "$1"/solver_cg_gamg_"$2"_procs_$nn.log -ksp_type cg -ksp_rtol "$3" -pc_type gamg
    done
}

rtol="1.0e-3"
casename=V100_tests/rtol_1e-3
mkdir -p log/"${casename}"
run_cg_gamg "${casename}" "${nb_cpu}" "${rtol}"

