#!/bin/bash -l
#SBATCH --job-name perfs
#SBATCH --time=00:30:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=36
#SBATCH --partition biggpu

export LD_LIBRARY_PATH=/softs/local_intel/petsc/3.13.4/lib:$LD_LIBRARY_PATH
nb_cpu=$SLURM_NPROCS

module list

run_solver() {
    for nn in 101 201 401 801 2001 4001
    do
        mpirun -np "$nb_cpu" ./poisson.out $nn $nn "$1"/"$2"_"$3"_"$nb_cpu"_procs_$nn.log -ksp_type "$2" -ksp_rtol "$4" -pc_type "$3"
    done
}

# rtol="1.0e-3"
# krylov_method="bicg"
# precond="jacobi"
# casename=log/solvers/"${krylov_method}"_"${precond}"/rtol_1e-3
# mkdir -p "${casename}"
# run_solver $casename $krylov_method $precond $rtol

rtol="1.0e-3"
krylov_method="bcgs"
precond="sor"
casename=log/solvers/"${krylov_method}"_"${precond}"/rtol_1e-3
mkdir -p "${casename}"
run_solver $casename $krylov_method $precond $rtol

