#!/bin/bash -l
#SBATCH --job-name perfs
#SBATCH --time=00:30:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=128
#SBATCH --partition rome

export LD_LIBRARY_PATH=/softs/local_intel/petsc/3.13.4/lib:$LD_LIBRARY_PATH
nb_cpu=$SLURM_NPROCS

source utils_cart.sh

# Study different solvers for cartesian matrix
# CG-GAMG / CG-Hypre-bommerang / LU and Cholesky

rtol="1.0e-3"
casename=log/cart/solvers/cg_gamg/"$nb_cpu"_procs/rtol_1e-3
mkdir -p "${casename}"
run_cg_gamg "${nb_cpu}" "${rtol}" "${casename}"

rtol="1.0e-6"
casename=log/cart/solvers/cg_gamg/"$nb_cpu"_procs/rtol_1e-6
mkdir -p "${casename}"
run_cg_gamg "${nb_cpu}" "${rtol}" "${casename}"

rtol="1.0e-10"
casename=log/cart/solvers/cg_gamg/"$nb_cpu"_procs/rtol_1e-10
mkdir -p "${casename}"
run_cg_gamg "${nb_cpu}" "${rtol}" "${casename}"

rtol="1.0e-12"
casename=log/cart/solvers/cg_gamg/"$nb_cpu"_procs/rtol_1e-12
mkdir -p "${casename}"
run_cg_gamg "${nb_cpu}" "${rtol}" "${casename}"

rtol="1.0e-3"
casename=log/cart/solvers/hypre_boomeramg/"$nb_cpu"_procs/rtol_1e-3
mkdir -p "${casename}"
run_cg_hypre_boomeramg "${nb_cpu}" "${rtol}" "${casename}"

rtol="1.0e-6"
casename=log/cart/solvers/hypre_boomeramg/"$nb_cpu"_procs/rtol_1e-6
mkdir -p "${casename}"
run_cg_hypre_boomeramg "${nb_cpu}" "${rtol}" "${casename}"

rtol="1.0e-10"
casename=log/cart/solvers/hypre_boomeramg/"$nb_cpu"_procs/rtol_1e-10
mkdir -p "${casename}"
run_cg_hypre_boomeramg "${nb_cpu}" "${rtol}" "${casename}"

rtol="1.0e-12"
casename=log/cart/solvers/hypre_boomeramg/"$nb_cpu"_procs/rtol_1e-12
mkdir -p "${casename}"
run_cg_hypre_boomeramg "${nb_cpu}" "${rtol}" "${casename}"

casename=log/cart/solvers/direct_lu/"$nb_cpu"_procs
mkdir -p "${casename}"
run_direct_cart "${nb_cpu}" lu "${casename}"

casename=log/cart/solvers/direct_cholesky/"$nb_cpu"_procs
mkdir -p "${casename}"
run_direct_cart "${nb_cpu}" cholesky "${casename}"
