#!/bin/bash -l
#SBATCH --job-name perfs
#SBATCH --time=00:30:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=36
#SBATCH --partition prod

export LD_LIBRARY_PATH=/softs/local_intel/petsc/3.13.4/lib:$LD_LIBRARY_PATH

casename=log/cart/single_case
mkdir -p "${casename}"
mpirun -np 36 ./src/poisson.out 2001 2001 "$casename"/perfs_unprecond_res_4mglevels_spd_eigen.log \
    -ksp_monitor_true_residual -ksp_norm_type unpreconditioned \
    -pc_mg_levels 4 \
    -ksp_type cg -ksp_rtol 1e-10 -pc_type gamg