########################################################################################################################
#                                                                                                                      #
#                                         NetworkPoisson -- Configuration file                                         #
#                                                                                                                      #
#                                           Lionel Cheng, CERFACS, 04.03.2021                                          #
#                                                                                                                      #
########################################################################################################################

# Contains the parameters for the model (training, etc.)

# To import the parameters, use
#     import yaml
#     with open('config.yml', 'r') as yaml_stream:
#         config = yaml.safe_load(yaml_stream)
eval:
    geom: 'cartesian'
    bcs: 'dirichlet'
    xmin: 0.0
    xmax: 1.0e-2
    nnx: 101
    ymin: 0.0
    ymax: 1.0e-2
    nny: 101
    nmax_fourier: 10

datasets: 
    random_8: '/scratch/cfd/PlasmaDL/datasets/eval/101x101/random_8'
    random_12: '/scratch/cfd/PlasmaDL/datasets/eval/101x101/random_12'
    random_16: '/scratch/cfd/PlasmaDL/datasets/eval/101x101/random_16'
    fourier_1: '/scratch/cfd/PlasmaDL/datasets/eval/101x101/fourier_1_0'
    fourier_3_0: '/scratch/cfd/PlasmaDL/datasets/eval/101x101/fourier_3_0'
    fourier_6_0: '/scratch/cfd/PlasmaDL/datasets/eval/101x101/fourier_6_0'

networks: 
    U3_K3_Rf50:
        resume: '/scratch/cfd/PlasmaDL/networks/train/RF_study/Unet/3_scales/k_3/RF_50/models/random_8'
        arch:
            db_file: 'unets_ks3_rf50.yml'
            name: 'UNet3'
            args:
                input_res: 101
    U4_K3_Rf50:
        resume: '/scratch/cfd/PlasmaDL/networks/train/RF_study/Unet/4_scales/k_3/RF_50/models/random_8'
        arch:
            db_file: 'unets_ks3_rf50.yml'
            name: 'UNet4'
            args:
                input_res: 101
    U3_K3_rf75:
        resume: '/scratch/cfd/PlasmaDL/networks/train/RF_study/Unet/3_scales/k_3/RF_75/models/random_8'
        arch:
            db_file: 'unets_ks3_rf75.yml'
            name: 'UNet3'
            args:
                input_res: 101
    U4_K3_rf75:
        resume: '/scratch/cfd/PlasmaDL/networks/train/RF_study/Unet/4_scales/k_3/RF_75/models/random_8'
        arch:
            db_file: 'unets_ks3_rf75.yml'
            name: 'UNet4'
            args:
                input_res: 101
    U3_K3_Rf100:
        resume: '/scratch/cfd/PlasmaDL/networks/train/RF_study/Unet/3_scales/k_3/RF_100/models/random_8'
        arch:
            db_file: 'unets_ks3_rf100.yml'
            name: 'UNet3'
            args:
                input_res: 101
    U4_K3_Rf100:
        resume: '/scratch/cfd/PlasmaDL/networks/train/RF_study/Unet/4_scales/k_3/RF_100/models/random_8'
        arch:
            db_file: 'unets_ks3_rf100.yml'
            name: 'UNet4'
            args:
                input_res: 101
    U5_K3_Rf100:
        resume: '/scratch/cfd/PlasmaDL/networks/train/RF_study/Unet/5_scales/k_3/RF_100/models/random_8'
        arch:
            db_file: 'unets_ks3_rf100.yml'
            name: 'UNet5'
            args:
                input_res: 101
    U3_K5_Rf100:
        resume: '/scratch/cfd/PlasmaDL/networks/train/RF_study/Unet/3_scales/k_5/RF_100/models/random_8'
        arch:
            db_file: 'unets_ks5_rf100.yml'
            name: 'UNet3'
            args:
                input_res: 101
    U4_K5_Rf100:
        resume: '/scratch/cfd/PlasmaDL/networks/train/RF_study/Unet/4_scales/k_5/RF_100/models/random_8'
        arch:
            db_file: 'unets_ks5_rf100.yml'
            name: 'UNet4'
            args:
                input_res: 101
    U3_K3_Rf150:
        resume: '/scratch/cfd/PlasmaDL/networks/train/RF_study/Unet/3_scales/k_3/RF_150/models/random_8'
        arch:
            db_file: 'unets_ks3_rf150.yml'
            name: 'UNet3'
            args:
                input_res: 101
    U4_K3_Rf150:
        resume: '/scratch/cfd/PlasmaDL/networks/train/RF_study/Unet/4_scales/k_3/RF_150/models/random_8'
        arch:
            db_file: 'unets_ks3_rf150.yml'
            name: 'UNet4'
            args:
                input_res: 101
    U5_K3_Rf150:
        resume: '/scratch/cfd/PlasmaDL/networks/train/RF_study/Unet/5_scales/k_3/RF_150/models/random_8'
        arch:
            db_file: 'unets_ks3_rf150.yml'
            name: 'UNet5'
            args:
                input_res: 101
    U3_K5_Rf150:
        resume: '/scratch/cfd/PlasmaDL/networks/train/RF_study/Unet/3_scales/k_5/RF_150/models/random_8'
        arch:
            db_file: 'unets_ks5_rf150.yml'
            name: 'UNet3'
            args:
                input_res: 101
    U4_K5_Rf150:
        resume: '/scratch/cfd/PlasmaDL/networks/train/RF_study/Unet/4_scales/k_5/RF_150/models/random_8'
        arch:
            db_file: 'unets_ks5_rf150.yml'
            name: 'UNet4'
            args:
                input_res: 101
    U3_K3_Rf200:
        resume: '/scratch/cfd/PlasmaDL/networks/train/RF_study/Unet/3_scales/k_3/RF_200/models/random_8'
        arch:
            db_file: 'unets_ks3_rf200.yml'
            name: 'UNet3'
            args:
                input_res: 101
    U4_K3_Rf200:
        resume: '/scratch/cfd/PlasmaDL/networks/train/RF_study/Unet/4_scales/k_3/RF_200/models/random_8'
        arch:
            db_file: 'unets_ks3_rf200.yml'
            name: 'UNet4'
            args:
                input_res: 101
    U5_K3_Rf200:
        resume: '/scratch/cfd/PlasmaDL/networks/train/RF_study/Unet/5_scales/k_3/RF_200/models/random_8'
        arch:
            db_file: 'unets_ks3_rf200.yml'
            name: 'UNet5'
            args:
                input_res: 101
    U3_K5_Rf200:
        resume: '/scratch/cfd/PlasmaDL/networks/train/RF_study/Unet/3_scales/k_5/RF_200/models/random_8'
        arch:
            db_file: 'unets_ks5_rf200.yml'
            name: 'UNet3'
            args:
                input_res: 101
    U4_K5_Rf200:
        resume: '/scratch/cfd/PlasmaDL/networks/train/RF_study/Unet/4_scales/k_5/RF_200/models/random_8'
        arch:
            db_file: 'unets_ks5_rf200.yml'
            name: 'UNet4'
            args:
                input_res: 101
    U5_K5_Rf200:
        resume: '/scratch/cfd/PlasmaDL/networks/train/RF_study/Unet/5_scales/k_5/RF_200/models/random_8'
        arch:
            db_file: 'unets_ks5_rf200.yml'
            name: 'UNet5'
            args:
                input_res: 101

network:
    casename: 'data'                          # Experience name
    n_gpu: 1                                    # Number of GPUs to use

    globals:                                    # Domain sizes and others, used to compute global attributes
        nnx: 101
        nny: 101
        xmin: 0.0
        xmax: 1.0e-2
        ymin: 0.0
        ymax: 1.0e-2
        coord: 'cart'
        verbosity: 2

    data_loader:
        type: 'PoissonDataLoader'
        data_channels: 1
        pipe_config: True
        args:
            batch_size: 25
            shuffle: True
            validation_split: 0.0               # if float, fraction of the full dataset, if int, length of validation portion
            num_workers: 4
            normalize: 'analytical'                   # max, physical or no for normalization types
            alpha: 0.1
            scaling_factor: 1.0e+6

    initializer: 'off'

    loss:
        type: 'ComposedLoss'
        pipe_config: True                       # Object initialization require config as first argument
        args:
            loss_list:                          # List of the losses to compose if ComposedLoss is used
                #- InsideLoss
                - DirichletBoundaryLoss
                - LaplacianLoss
            inside_weight: 0.                   # Weighting of the loss inside the domain, excluding boundaries (float)
            bound_weight: 1.                    # Weighting of the loss on the boundaries (float)
            elec_weight: 0.                     # Weighting of the loss on the electric field (float)
            lapl_weight: 0.1                    # Weighting of the loss on the Laplacian (float)

    metrics:
        - 'residual'
        - 'inf_norm'
        - 'Eresidual'
        - 'Einf_norm'
        - 'phi11'
        - 'phi21'
        - 'phi12'
        - 'phi22'
    