#!/usr/bin/bash
#SBATCH --gres=gpu:1
#SBATCH --job-name=PlasmaNet
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=12
#SBATCH --time=08:00:00
#SBATCH --partition=gpu

source /scratch/cfd/bogopolsky/DL/dl_env/bin/activate

python train.py -c config.yml
