########################################################################################################################
#                                                                                                                      #
#                                           PlasmaNet -- Configuration file                                            #
#                                                                                                                      #
#                                      Guillaume Bogopolsky, CERFACS, 11.03.2020                                       #
#                                                                                                                      #
########################################################################################################################

# Contains the parameters for the model (training, etc.)

# To import the parameters, use
#     import yaml
#     with open('config.yml', 'r') as yaml_stream:
#         config = yaml.safe_load(yaml_stream)

# The train routine will automatically load the required `type` of each section with the given `args` by using the
# `config.init_obj` method.


name: 'gauss_64'                            # Experience name
n_gpu: 1                                    # Number of GPUs to use

globals:                                    # Domain sizes and others, used to compute global attributes
    size: 64.
    length: 0.01


arch:
    type: 'MultiSimpleNet'
    args:
        data_channels: 1

data_loader:
    type: 'PoissonDataLoader'
    args:
        data_dir: 'datasets/64x64/sliding_gaussian_zerofield'
        batch_size: 128
        shuffle: True
        validation_split: 0.2               # if float, fraction of the full dataset, if int, length of validation portion
        num_workers: 4
        normalize: 'max'                    # max, physical or none for normalization types

initializer: 'off'

optimizer:
    type: 'Adam'
    args:
        lr: 4.e-4
        weight_decay: 0
        amsgrad: False                      # AMSGrad variant from paper 'On the convergence of Adam and Beyond'

loss:
    type: 'ComposedLoss'
    pipe_config: True                       # Object initialization require config as first argument
    args:
        loss_list:                          # List of the losses to compose if ComposedLoss is used
            - InsideLoss
            - DirichletBoundaryLoss
            - LaplacianLoss
        inside_weight: 1.                   # Weighting of the loss inside the domain, excluding boundaries (float)
        bound_weight: 1.                    # Weighting of the loss on the boundaries (float)
        elec_weight: 0.                     # Weighting of the loss on the electric field (float)
        lapl_weight: 0.1                    # Weighting of the loss on the Laplacian (float)

metrics:
    - 'residual'
    - 'l2_norm'
    - 'inf_norm'

lr_scheduler:
    type: 'ReduceLROnPlateau'
    args:
        mode: 'min'
        factor: 0.99                        # Amount scheduler reduces LR by (float)
        patience: 50                        # Number of epochs the scheduler waits (int)
        threshold: 3.e-4                    # Relative improvement the scheduler must see (float)
        threshold_mode: 'rel'
        verbose: False

trainer:
    epochs: 1000
    save_dir: 'outputs/'
    save_period: 10
    plot_period: 10                         # Period to send plots to TensorBoard
    verbosity: 2
    monitor: min val_loss                   # Monitor best model ('method metric', method={min, max}, metric exists)
    early_stop: 200                         # Training is stopped if model performance does not increase for 50 epochs
    tensorboard: true
