#!/usr/bin/bash
#SBATCH --gres=gpu:1
#SBATCH --job-name=PlasmaNet
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=9
#SBATCH --time=08:00:00
#SBATCH --partition=gpu
#SBATCH --nodelist=krakengpu2

python train.py -c config.yml
