#!/usr/bin/bash
#SBATCH --job-name=PlasmaNet
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=3
#SBATCH --time=01:00:00
#SBATCH --partition=rome
#SBATCH --nodelist=krakenepyc1

run_cases -np 3 -c poscill_101_cases.yml -t pleuler