########################################################################################################################
#                                                                                                                      #
#                                            cfdsolver -- Configuration file                                           #
#                                                                                                                      #
#                                           Lionel Cheng, CERFACS, 27.03.2020                                          #
#                                                                                                                      #
########################################################################################################################

# Contains the parameters for the model (training, etc.)

# To import the parameters, use
#     import yaml
#     with open('config.yml', 'r') as yaml_stream:
#         config = yaml.safe_load(yaml_stream)

casename: 'a_D_perio_x_1/'

params:
  nit: 100

mesh:
  xmin: 0
  ymin: 0
  xmax: 1
  ymax: 1
  nnx: 501
  nny: 501

transport:
  convection_x: 1
  convection_y: 0.5
  diffusion: 0.001

BC: 'perio_x'

output:
  save: 'none'
  verbose: True
  period: 10