#!/usr/bin/bash
#SBATCH --job-name=PlasmaNet
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --time=01:00:00
#SBATCH --partition=prod
# #SBATCH --partition=biggpu
# #SBATCH --nodelist=krakenepyc1

run_cases -np 4 -c dh_streamer_cases_dt.yml -t streamer