#!/usr/bin/bash
#SBATCH --job-name=PlasmaNet
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=6
#SBATCH --time=01:00:00
#SBATCH --partition=gpu
#SBATCH --nodelist=krakengpu2

run_cases -np 6 -c $1 -t pleuler