#####################################################################################
#                                                                                   #
#                       Benchmark config -- Configuration file                      #
#                                                                                   #
#                      Guillaume Bogopolsky, CERFACS, 28.06.2021                    #
#                                                                                   #
#####################################################################################

sizes: [51, 101, 121, 201, 301, 401, 601, 801, 1001, 1501, 2001, 3001]
# sizes: [51, 101, 121, 201]
solver_types: ["direct"]
useUmfpack: [True]
assumeSortedIndices: [True]
nits: 200

# Networks to test
networks:
  U3_K3_Rf200:
    resume: '/scratch/cfd/PlasmaDL/networks/train/RF_study/Unet/3_scales/k_3/RF_200/models/random_8'
    arch:
      db_file: 'unets_ks3_rf200.yml'
      name: 'UNet3'
      args:
        input_res: 101
  #U4_K3_Rf200:
  #  resume: '/scratch/cfd/PlasmaDL/networks/train/RF_study/Unet/4_scales/k_3/RF_200/models/random_8'
  #  arch:
  #    db_file: 'unets_ks3_rf200.yml'
  #    name: 'UNet4'
  #    args:
  #      input_res: 101
  U5_K3_Rf200:
    resume: '/scratch/cfd/PlasmaDL/networks/train/RF_study/Unet/5_scales/k_3/RF_200/models/random_8'
    arch:
      db_file: 'unets_ks3_rf200.yml'
      name: 'UNet5'
      args:
        input_res: 101
  UNet5-200k:
    resume: "/scratch/cfd/PlasmaDL/networks/train/nparams/300to700epochs/models/200k/"
    arch:
      db_file: "unets5_ks3_nparams.yml"
      name: "UNet5-200k"
      args:
        input_res: 101
  UNet5-400k:
    resume: "/scratch/cfd/PlasmaDL/networks/train/nparams/300to700epochs/models/400k/"
    arch:
      db_file: "unets5_ks3_nparams.yml"
      name: "UNet5-400k"
      args:
        input_res: 101
  UNet5-800k:
    resume: "/scratch/cfd/PlasmaDL/networks/train/nparams/300to700epochs/models/800k/"
    arch:
      db_file: "unets5_ks3_nparams.yml"
      name: "UNet5-800k"
      args:
        input_res: 101
