#####################################################################################
#                                                                                   #
#                       Benchmark config -- Configuration file                      #
#                                                                                   #
#                          Lionel Cheng, CERFACS, 28.06.2021                        #
#                                                                                   #
#####################################################################################

nnx: [201, 401, 601, 801]
nny: [51, 101, 151, 201]
solver_types: ["direct"]
useUmfpack: [False]
assumeSortedIndices: [False]
nits: 10
