#!/bin/bash -l
#SBATCH --job-name perf_A100
#SBATCH --time=00:30:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=128
#SBATCH --partition rome

/scratch/cfd/cheng/DL/dl_env/bin/python network_bench.py \
    -n 101 201 401 801 2001 4001 5001 5501 6001 \
    -cn cases/bench_A100/