#!/usr/bin/bash
#SBATCH --job-name=POscillNet
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=36
#SBATCH --time=10:00:00
#SBATCH --partition=gpu
#SBATCH --nodelist=krakengpu2

python run_cases.py -c dl_poscill_101_cases_scales.yml -np 6