#!/usr/bin/bash
#SBATCH --job-name=POscillNet
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=30
#SBATCH --time=10:00:00
#SBATCH --partition=gpu
#SBATCH --nodelist=krakengpu1

run_cases -np 5 -c poscill_101_cases.yml -t pleuler