########################################################################################################################
#                                                                                                                      #
#                                            cfdsolver -- Configuration file                                           #
#                                                                                                                      #
#                                           Lionel Cheng, CERFACS, 27.03.2020                                          #
#                                                                                                                      #
########################################################################################################################

# Contains the parameters for the model (training, etc.)

# To import the parameters, use
#     import yaml
#     with open('config.yml', 'r') as yaml_stream:
#         config = yaml.safe_load(yaml_stream)

casename: 'dh_streamer_11/'

params:
  nit: 100
  dt: 5.0e-13
  geom: 'xr'
  photoionization: 'three'

mesh:
  xmin: 0
  ymin: 0
  xmax: 0.004
  ymax: 0.001
  nnx: 401
  nny: 101

transport:
  chemistry: 'morrow'

poisson:
  backE: 4.8e+6

output:
  folder: 'data/'
  save: 'iteration'
  verbose: True
<<<<<<< HEAD
  files: 'figdata'
  period: 50
=======
  files: 'fig'
  folder: 'data/'
  period: 100
>>>>>>> 4667bb0964cc2e271c35a1000aef7104552d6271
  dl_save: 'yes'

input: 'none'
  # ne: 'data/dh_streamer_7/ne_0004.npy'
  # np: 'data/dh_streamer_7/np_0004.npy'
  # nn: 'data/dh_streamer_7/nn_0004.npy'
