########################################################################################################################
#                                                                                                                      #
#                                            cfdsolver -- Configuration file                                           #
#                                                                                                                      #
#                                           Lionel Cheng, CERFACS, 27.03.2020                                          #
#                                                                                                                      #
########################################################################################################################

# Contains the parameters for the model (training, etc.)

# To import the parameters, use
#     import yaml
#     with open('config.yml', 'r') as yaml_stream:
#         config = yaml.safe_load(yaml_stream)

casename: 'a_D_x/'

params:
  nit: 100
  cfl: 0.5
  fourier: 0.15
  geom: 'xy'

mesh:
  xmin: 0
  ymin: 0
  xmax: 1
  ymax: 1
  nnx: 101
  nny: 101

transport:
  convection_x: 1
  convection_y: 0
  diffusion: 0.000

BC: 'full_out'

output:
  save: 'iteration'
  verbose: True
  period: 10