#############################################################################################################
#                                                                                                           #
#                            PlasmaNet -- Architectures with around 100 000 params                          #
#                                                                                                           #
#                                     Lionel Cheng, CERFACS, 05.05.2021                                     #
#                                                                                                           #
#############################################################################################################
# UNet3:
#     type: 'UNet'
#     args:
#       scales:
#         depth_0: [[1, 20, 20, 20, 20, 20], [44, 20, 20, 20, 20, 1]]
#         depth_1: [[20, 20, 20, 20, 20, 20], [44, 20, 20, 20, 20, 24]]
#         depth_2: [20, 24, 24, 24, 24, 24]
#       kernel_sizes: 3

MSNet3:
    type: 'MSNet'
    args:
      scales: 
        depth_0: [2, 26, 26, 26, 26, 26, 26, 26, 8, 1]
        depth_1: [2, 26, 26, 26, 26, 26, 26, 1]
        depth_2: [1, 26, 26, 26, 26, 26, 26, 1]
      kernel_sizes: 3