#############################################################################################################
#                                                                                                           #
#                            PlasmaNet -- Architectures with around 100 000 params                          #
#                                                                                                           #
#                                     Lionel Cheng, CERFACS, 05.05.2021                                     #
#                                                                                                           #
#############################################################################################################
# UNet3:
#     type: 'UNet'
#     args:
#       scales:
#         depth_0: [[1, 20, 20, 20, 20, 20], [44, 20, 20, 20, 20, 1]]
#         depth_1: [[20, 20, 20, 20, 20, 20], [44, 20, 20, 20, 20, 24]]
#         depth_2: [20, 24, 24, 24, 24, 24]
#       kernel_sizes: 3

UNet4:
    type: 'UNet'
    args:
      scales:
        depth_0: [[1, 16, 16, 16, 16, 18], [36, 16, 16, 16, 16, 1]]
        depth_1: [[18, 16, 16, 16, 16, 18], [36, 16, 16, 16, 16, 18]]
        depth_2: [[18, 16, 16, 16, 16, 18], [36, 16, 16, 16, 16, 18]]
        depth_3: [18, 24, 24, 24, 24, 18]
      kernel_sizes: 3

# MSNet3:
#     type: 'MSNet'
#     args:
#       scales: 
#         depth_0: [2, 26, 26, 26, 26, 26, 26, 26, 8, 1]
#         depth_1: [2, 26, 26, 26, 26, 26, 26, 1]
#         depth_2: [1, 26, 26, 26, 26, 26, 26, 1]
#       kernel_sizes: 3

MSNet4:
    type: 'MSNet'
    args:
        scales:
          depth_0: [2, 24, 24, 24, 22, 22, 22, 8, 1]
          depth_1: [2, 26, 26, 26, 26, 26, 1]
          depth_2: [2, 24, 24, 24, 22, 22, 22, 1]
          depth_3: [1, 24, 24, 24, 22, 22, 22, 1]
        kernel_sizes: 3