#####################################################################################
#                                                                                   #
#                        PoissonLinSystem -- Configuration file                     #
#                                                                                   #
#                          Lionel Cheng, CERFACS, 04.03.2021                        #
#                                                                                   #
#####################################################################################

# Contains the parameters for the model (training, etc.)

# To import the parameters, use
#     import yaml
#     with open('config.yml', 'r') as yaml_stream:
#         config = yaml.safe_load(yaml_stream)

device: 'kraken'
n_entries: 10000
n_procs: 30
output_dir: '/scratch/cfd/cheng/DL/datasets/train/'

poisson:
  mat: 'cart_dirichlet'
  xmin: 0.0
  xmax: 1.0e-2
  nnx: 101
  ymin: 0.0
  ymax: 1.0e-2
  nny: 101
  nmax_fourier: 5