#!/usr/bin/bash
#SBATCH --job-name=POscillNet
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=36
#SBATCH --time=10:00:00
#SBATCH --partition=biggpu

python run_cases.py -c dl_poscill_101_cases_resolution.yml -np 6